name: Reusable action for dependencies installation

runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        shell: bash

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-pkg-manager-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-pkg-manager-
      
      - if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        name: Update dependencies
        run: yarn
        shell: bash

      - if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        name: Update dependencies from local cache
        run: yarn --prefer-offline
        shell: bash