name: Test/ Code analysis on Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  analysis:
    name: Run Static Analysis
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-pkg-manager-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-pkg-manager-
      
      - if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        name: Update dependencies
        run: yarn

      - if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        name: Update dependencies from local cache
        run: yarn --prefer-offline

      - name: Run eslint
        run: yarn lint

  e2e:
    name: Run e2e
    needs: analysis
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup detox environment
        run: |
        brew tap wix/brew
        brew install applesimutils
        npm i -g detox-cli

      - name: trigger the e2e build & test
        run: yarn detox:e2e-ios-ci