name: Test/ Code analysis on Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  analysis:
    name: Run Static Analysis
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/dependencies

      - name: Run eslint
        run: yarn lint

  e2e:
    name: Run e2e
    needs: analysis
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/dependencies

      - name: Setup detox environment
        run: brew tap wix/brew && brew install applesimutils && npm i -g detox-cli

      - uses: actions/cache@v3
        id: pod-cache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup pods
        if: steps.pod-cache.outputs.cache-hit != 'true'
        run: cd ios && pod install && cd .. 

      - name: trigger the e2e build & test
        run: yarn detox:e2e-ios-ci